input {
  tcp {
    port => 5000
    codec => json_lines
  }
  udp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [logger_name] {
    mutate {
      add_field => { "application" => "%{[logger_name]}" }
    }
  }

  if [level] {
    mutate {
      add_field => { "log_level" => "%{[level]}" }
    }
  }

  date {
    match => ["timestamp", "ISO8601", "yyyy-MM-dd HH:mm:ss.SSS"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "online-cart-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
