apiVersion: v1
kind: Secret
metadata:
  name: online-cart-secrets
  namespace: online-cart
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_USER: "onlinecart"
  MYSQL_PASSWORD: "onlinecart123"
  REDIS_PASSWORD: ""
